recon_service_node:
    gridm: 0.8
    holemaxsize: 2.0
    output_folder: $(find map_builder)/tmp_reconstructions/
    sample: 1.0
    texturesize: 320.0
    trim: 6.5
    remove_borders_iterations: 1.0
    